### ISSUE TITLE
libraries\ModbusMaster-master/ModbusMaster.h:83:24: fatal error: util/crc16.h: No such file or directory

### ISSUE THREAD

**Issue by Cristianistrate** [JCSCatena/PZEM004Tv30_MODBUS#1]
Why dist error ?
Can you help me ?
Thank you!

**Comment by commonslibs** [comment]
Same problem here https://github.com/CurtRod/SimpleEVSE-WiFi/issues/12

Verify MBUSmaster project.

In principle the problem is not from the library.

A greeting.
